_step:
    path:   'clevermanagement/step'
    controller:   'StepController'
    action: 'index'

_step_show:
    path:   'clevermanagement/step/:id'
    controller:   'StepController'
    action: 'find'
    filters:
        require:
            id: '[1-9]+'

_step_create:
    path:   'clevermanagement/step/create'
    controller:   'StepController'
    action: 'create'

_step_delete:
    path:   'clevermanagement/step/:id/delete'
    controller:   'StepController'
    action: 'delete'
    filters:
        require:
            id: '[1-9]+'

_step_edit:
    path:   'clevermanagement/step/:id/edit'
    controller:   'StepController'
    action: 'edit'
    filters:
        require:
            id: '[1-9]+'
