_step_show:
    path: 'clevermanagement/:id_project/show/step/:id/show'
    controller: 'StepController'
    action: 'find'
    filters:
        require:
            id: '[0-9]+'

_step_create:
    path: 'clevermanagement/:id_project/show/step/create'
    controller: 'StepController'
    action: 'create'

_step_delete:
    path: 'clevermanagement/:id_project/show/:id_step/delete'
    controller: 'StepController'
    action: 'delete'
    filters:
        require:
            id: '[0-9]+'

_step_edit:
    path: 'clevermanagement/:id_project/show/step/:id_step/edit'
    controller: 'StepController'
    action: 'edit'
    filters:
        require:
            id: '[0-9]+'
