# Routes

_home:
    path:   'clevermanagement'
    controller:   'HelloController'
    action: 'run'
    method: 'GET'

_register:
    path:   'clevermanagement/signup'
    controller:   'UserController'
    action: 'signup'
    method: 'POST'

login:
    path:   'clevermanagement/signin'
    controller:   'UserController'
    action: 'signin'
    method: 'POST'