_project:
    path: 'clevermanagement'
    controller: 'ProjectController'
    action: 'index'

_project_create:
    path: 'clevermanagement/create'
    controller: 'ProjectController'
    action: 'create'
    method: 'POST'

_project_show:
    path: 'clevermanagement/:id/show'
    controller: 'ProjectController'
    action: 'show'
    filters:
        require:
            id: '[1-9]+'

_project_delete:
    path:   'clevermanagement/:id/delete'
    controller:   'ProjectController'
    action: 'delete'
    filters:
        require:
            id: '[1-9]+'

_project_edit:
	path:   'clevermanagement/:id/edit'
	controller:   'ProjectController'
	action: 'edit'
	method: 'POST'