_task_create:
    path: 'clevermanagement/:id_project/show/step/:id_step/show/task/create'
    controller: 'taskController'
    action: 'create'

_task_delete:
    path: 'clevermanagement/:id_project/show/step/:id_step/show/task/:id_task/delete'
    controller: 'taskController'
    action: 'delete'
    filters:
        require:
            id: '[0-9]+'

_task_edit:
    path: 'clevermanagement/:id_project/show/step/:id_step/show/task/:id_task/edit'
    controller: 'taskController'
    action: 'edit'
    filters:
        require:
            id: '[0-9]+'
