_project:
    path: 'clevermanagement/project'
    controller: 'ProjectController'
    action: 'index'

_project_create:
    path: 'clevermanagement/project/create'
    controller: 'ProjectController'
    action: 'create'
    method: 'POST'

#_project_show:
#    path:'clevermanagement/project/:id'
#    controller: 'ProjectController'
#    action: 'find'

_project_delete:
    path:   'clevermanagement/project/:id/delete'
    controller:   'ProjectController'
    action: 'delete'
    filters:
        require:
            id: '[1-9]+'
