# Routes

_home:
    path:   'clevermanagement'
    controller:   'HelloController'
    action: 'run'
    method: 'GET'

_user:
    path:   'clevermanagement/user'
    controller:   'UserController'
    action: 'run'
    method: 'GET'