# Routes

_register:
    path: 'clevermanagement/signup'
    controller: 'UserController'
    action: 'signup'
    method: 'POST'

_login:
    path: 'clevermanagement/signin'
    controller: 'UserController'
    action: 'signin'
    method: 'POST'

_destroy:
	path: 'clevermanagement/deconnection'
	controller: 'UserController'
	action: 'destroy'

#_logout:
#    path: 'clevermanagement/signin'
#    controller: 'UserController'
#    action: 'signout'
#    method: 'POST'