# Routes

_home:
    path:   'clevermanagement'
    controller:   'UserController'
    action: 'signin'

_register:
    path: 'clevermanagement/signup'
    controller: 'UserController'
    action: 'signup'
    method: 'POST'

_login:
    path: 'clevermanagement/signin'
    controller: 'UserController'
    action: 'signin'
    method: 'POST'