_directory_create:
    path: 'clevermanagement/directory/create'
    controller: 'DirectoryController'
    action: 'create'
    method: 'POST'

_directory_show:
    path: 'clevermanagement/directory/:id/show'
    controller: 'DirectoryController'
    action: 'show'
    filters:
        require:
            id: '[0-9]+'

_directory_delete:
    path: 'clevermanagement/directory/:id/delete'
    controller: 'DirectoryController'
    action: 'delete'
    filters:
        require:
            id: '[0-9]+'

_directory_edit:
    path: 'clevermanagement/directory/:id/edit'
    controller: 'DirectoryController'
    action: 'edit'
    method: 'POST'
