_task_create:
    path: 'clevermanagement/:id_project/step/:id_step/task/create'
    controller: 'taskController'
    action: 'create'

_task_show:
    path: 'clevermanagement/:id_project/step/:id_step/task/:id_task/show'
    controller: 'taskController'
    action: 'show'

_task_delete:
    path: 'clevermanagement/:id_project/step/:id_step/task/:id_task/delete'
    controller: 'taskController'
    action: 'delete'
    filters:
        require:
            id: '[0-9]+'

_task_edit:
    path: 'clevermanagement/:id_project/step/:id_step/task/:id_task/edit'
    controller: 'taskController'
    action: 'edit'
    filters:
        require:
            id: '[0-9]+'

_task_done:
    path: 'clevermanagement/:id_project/step/:id_step/task/:id_task/done'
    controller: 'taskController'
    action: 'done'
    filters:
        require:
            id: '[0-9]+'
