# Form exemple

form_project_create:
  form:
    method: POST
    action: /clevermanagement/create
    submit: Valider
    structure: table

  fields:
    name:
      type: text
      label: Name
      required: false
      style: width:300px;height:30px;
    startline:
      type: date
      label: Startline
      required: false
      style: width:300px;height:30px;
    deadline:
      type: date
      label: Deadline
      required: false
      style: width:300px;height:30px;
    description:
      type: textarea
      label: Description
      required: false
      rows: "5"
      cols: "100"
    members:
      type: hidden
      id: members-project
      placeholder: Members
      style: width:300px;height:100px;
    additionalAdmins:
      type: hidden
      id: add-admin-project
      label: Ajouter des Admin-Project
      placeholder: Additional Admin-Project
      style: width:300px;height:100px;
    dierctory:
      type: hidden
      id: directory-project
      label: Ranger dans le dossier
      placeholder: Nom de dossier

