form_task_create:
  form:
    method: POST
    action: /clevermanagement/task/create
    submit: Create
    structure: table

  fields:
    type:
      type: hidden
      value: task-create
    name:
      type: text
      required: true
      label: Name
    description:
      type: textarea
      required: true
      label: Description
      check:
        min: 50
    urgent:
      type: checkbox
      options:
        1:
          label: 'Urgent'
    startline:
      type: date
      required: true
      label: Startline
    deadline:
      type: date
      required: true
      label: Deadline
