form_directory_create:
  form:
    method: POST
    action: /clevermanagement/directory/create
    submit: Valider
    structure: table

  fields:
    name:
      type: text
      required: true
      label: Nom
