form_signup:
  form:
    method: POST
    action: /clevermanagement/signup
    submit: Sign up
    structure: table
    class: form-signin

  fields:
    type:
      type: hidden
      value: signup
      label: false
    firstname:
      type: text
      required: true
      label: Firstname
      class: input-block-level
    lastname:
      type: text
      required: true
      label: Lastname
      class: input-block-level
    email:
      type: text
      required: true
      label: Email
      class: input-block-level
      check:
        validate: /^\w{3,10}$/
    password:
      type: password
      id: helloworld
      class: input-block-level
      check:
        required: true
    job:
      type: text
      required: true
      label: Job
      class: input-block-level
    hour_price:
      type: text
      required: true
      label: Hour Price
      class: input-block-level