# Form exemple

form_project_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/edit
    submit: Editer
    structure: table

  fields:
    name:
      type: text
      label: Name
      required: false
    startline:
      type: date
      label: Startline
      required: false
    deadline:
      type: date
      label: Deadline
      required: false
    description:
      type: textarea
      label: Description
      required: false
    members:
      type: hidden
      id: members-project
      placeholder: Members
      style: width:300px;;height:100px;
    additionalAdmins:
      type: hidden
      id: add-admin-project
      label: Additional Admin-Project
      placeholder: Additional Admin-Project
      style: width:300px;;height:100px;

