form_task_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/task/id_task/edit
    submit: Editer
    structure: table

  fields:
    name:
      type: text
      required: true
      label: Name
      check:
        min: 3
    description:
      type: textarea
      required: true
      label: Description
      check:
        min: 5
    urgent:
      type: checkbox
      options:
        1:
          label: 'Urgent'
      check:
        required: false
    startline:
      type: date
      required: true
      label: Startline
    deadline:
      type: date
      required: true
      label: Deadline
    members:
      type: select
      multiple: true
      label: 'Rajouter membres'
      name: 'members[]'
      options:
        - email1
        - email2
        - email3
    registeredMembers:
      type: checkbox
      label: 'Supprimer membres'
      function: 'TaskController::getRegisteredMembers([id_task:id_task])'
      check:
        required: false
