form_session_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/task/id_task/session/edit
    submit: Valider
    structure: table

  fields:
    hour_number:
      type: text
      required: true
      label: Heure(s) travaillée(s)
      check:
        max: 3
    percent:
      type: text
      required: true
      label: Estimer la tache en %
      check:
        max: 3
    comment:
      type: text
      required: true
      label: Commentaire
      check:
        min: 5
