form_session_create:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/task/id_task/session/create
    submit: Cr&eacute;er une session
    structure: table

  fields:
    hour_number:
      type: text
      required: true
      label: Heure(s) travaill&eacute;(s)
      check:
        max: 3
    percent:
      type: text
      required: true
      label: Estimer la tache en %
      check:
        max: 3
    comment:
      type: text
      required: true
      label: Commentaire

