form_signin:
  form:
    method: POST
    action: /clevermanagement/signin
    submit: Sign up
    structure: table

  fields:
    type:
      type: hidden
      value: signup
    email:
      type: text
      required: true
      label: Email
      check:
        validate: /^\w{3,10}$/
    password:
      type: password
      id: helloworld
      check:
        required: true

