# Form exemple

form_project_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/edit
    submit: Editer
    structure: table

  fields:
    name:
      type: text
      label: Name
      required: false
      check:
        min: 5
    startline:
      type: date
      label: Startline
      required: false
    deadline:
      type: date
      label: Deadline
      required: false
    description:
      type: textarea
      label: Description
      required: false
      rows: "5"
      cols: "100"
      check:
        min: 5
    members:
      type: hidden
      id: members-project
      placeholder: Members
      style: width:300px;height:30px;margin-bottom:20px;
    additionalAdmins:
      type: hidden
      id: add-admin-project
      label: Additional Admin-Project
      placeholder: Additional Admin-Project
      style: width:300px;height:30px;margin-bottom:20px;
    directory:
      type: select
      multiple: false
      label: 'Ranger dans un dossier'
      name: 'directory'
      style: margin-top:20px;
      options:
        - directory1
        - directory2
        - directory3
