form_step_create:
  form:
    method: POST
    action: /clevermanagement/2/show/step/create
    submit: Create
    structure: table

  fields:
    type:
      type: hidden
      value: step-create
    name:
      type: text
      required: true
      label: Name
    description:
      type: textarea
      required: true
      label: Description
      check:
        min: 50
    startline:
      type: date
      required: true
      label: Startline
    deadline:
      type: date
      required: true
      label: Deadline