form_task_create:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/task/create
    submit: Valider
    structure: table

  fields:
    name:
      type: text
      required: true
      label: Name
      check:
        min: 3
    description:
      type: textarea
      required: true
      label: Description
      check:
        min: 5
    urgent:
      type: checkbox
      options:
        1:
          label: ' '
    startline:
      type: date
      required: true
      label: Startline
    deadline:
      type: date
      required: true
      label: Deadline
    members:
      type: select
      required: false
      label: Membres
      multiple: true
      name: 'members[]'
      options:
        - email1
        - email2
        - email3
