# Form exemple

form_project_create:
  form:
    method: POST
    action: /clevermanagement/project/create
    submit: Envoyer
    structure: table

  fields:
    name:
      type: text
      label: Name
      required: false
    startline:
      type: date
      label: Startline
      required: false
    deadline:
      type: date
      label: Deadline
      required: false
    description:
      type: textarea
      label: Description
      required: false

