form_directory_edit:
  form:
    method: POST
    action: /clevermanagement/directory/id_directory/edit
    submit: Editer
    structure: table

  fields:
    name:
      type: text
      required: true
      label: Nom
