form_session_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/task/id_task/session/edit
    submit: Valider
    structure: table

  fields:
    hour_number:
      type: text
      required: true
      label: Heures travaillé
    percent:
      type: text
      required: true
      label: éstimer la tache en %
    comment:
      type: text
      required: true
      label: commentaire
