form_signup:
  form:
    method: POST
    action: /clevermanagement/signup
    submit: Sign up
    structure: table

  fields:
    type:
      type: hidden
      value: signup
    firstname:
      type: text
      required: true
      label: Firstname
    lastname:
      type: text
      required: true
      label: Lastname
    email:
      type: text
      required: true
      label: Email
      check:
        validate: /^\w{3,10}$/
    password:
      type: password
      id: helloworld
      check:
        required: true
    job:
      type: text
      required: true
      label: Job
    hour_price:
      type: text
      required: true
      label: Hour Price

