form_step_edit:
  form:
    method: POST
    action: /clevermanagement/id_project/step/id_step/edit
    submit: Editer
    structure: table

  fields:
    name:
      type: text
      required: true
      label: Name
      check: 
        min: 3
    description:
      type: textarea
      required: true
      label: Description
      check:
        min: 5
    startline:
      type: date
      required: true
      label: Startline
    deadline:
      type: date
      required: true
      label: Deadline