# form_signup:
#   form:
#     method: POST
#     action: /my-form
#     submit: Sign up
#     structure: table

#   fields:
#     firstname:
#       type: text
#       required: true
#       label: Firstname
#     lastname:
#       type: text
#       required: true
#       label: Lastname
#     email:
#       type: text
#       required: true
#       label: Email
#       check:
#         validate: /^\w{3,10}$/
#     password:
#       type: password
#       id: helloworld
#       check:
#         required: true
#     job:
#       type: text
#       required: true
#       label: Job


