# Form exemple

form_project_create:
  form:
    method: POST
    action: /clevermanagement/create
    submit: Valider
    structure: table

  fields:
    name:
      type: text
      label: Name
      style: width:300px;height:30px;
      required: true
      check:
        min: 5
    startline:
      type: date
      label: Startline
      required: false
      style: width:300px;height:30px;
      check:
        required: true
    deadline:
      type: date
      label: Deadline
      required: false
      style: width:300px;height:30px;
      check:
        required: true
    description:
      type: textarea
      label: Description
      required: false
      rows: "5"
      cols: "100"
      check:
        required: true
        min: 5
    members:
      type: hidden
      id: members-project
      placeholder: Members
      style: width:300px;height:30px;margin-bottom:20px;
    additionalAdmins:
      type: hidden
      id: add-admin-project
      label: Ajouter des Admin-Project
      placeholder: Additional Admin-Project
      style: width:300px;height:30px;margin-bottom:20px;
    directory:
      type: select
      multiple: false
      label: 'Ranger dans un dossier'
      name: 'directory'
      options:
        - directory1
        - directory2
        - directory3
